Repository sendsmaily/smaily-prestashop-module, pull requests merged in 2020-11, with the labels that each got.

#34 Missing template variables caused errors
  smailyforprestashop.php
Labels: bug

#38 Use PrestashopLogger for logging
  controllers/front/SmailyCartCron.php
  controllers/front/SmailyCustomerCron.php
  smailyforprestashop.php
Labels: enhancement

#39 1.5.0 release
  CHANGELOG.md
  README.md
  USERGUIDE.md
  assets/CustomerSync.png
  controllers/front/SmailyCartCron.php
  controllers/front/SmailyCustomerCron.php
  smailyforprestashop.php
  translations/et.php
  upgrade/Upgrade-1.5.0.php
  views/js/smaily_module.js
  views/templates/admin/smaily_configure.tpl
Labels: release

#40 Rework development environment
  .docker/Dockerfile
  .docker/docker-compose.yml
  .docker/entrypoint.sh
  .github/pull_request_template.md
  .github/workflows/release.yaml
  .sandbox/entrypoint.sh
  CONTRIBUTING.md
  Dockerfile
  docker-compose.yaml
  modman
  src/controllers/admin/AdminSmailyforprestashopAjaxController.php
  src/controllers/admin/index.php
  src/controllers/front/SmailyCartCron.php
  src/controllers/front/SmailyCustomerCron.php
  src/controllers/front/SmailyRssFeed.php
  src/controllers/front/index.php
  src/controllers/index.php
  src/index.php
  src/logo.png
  src/smailyforprestashop.php
  src/translations/et.php
  src/translations/index.php
  src/upgrade/Upgrade-1.1.0.php
  src/upgrade/Upgrade-1.3.0.php
  src/upgrade/Upgrade-1.5.0.php
  src/upgrade/index.php
  src/views/index.php
  src/views/js/index.php
  src/views/js/smaily_module.js
  src/views/templates/admin/index.php
  src/views/templates/admin/smaily_configure.tpl
  src/views/templates/hook/index.php
  src/views/templates/hook/smaily_blocknewsletter.tpl
  src/views/templates/hook/smaily_blocknewsletter_column.tpl
  src/views/templates/index.php
  tusk.yml
Labels: documentation, enhancement, maintenance
