Repository sendsmaily/smaily-prestashop-module, pull requests merged in 2020-08, with the labels that each got.

#17 Allow parameters for RSS feed, generate RSS URL in user friendly manner
  README.md
  controllers/front/SmailyRssFeed.php
  smailyforprestashop.php
  translations/et.php
  views/js/smaily_module.js
  views/templates/admin/smaily_configure.tpl
Labels: enhancement

#23 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: maintenance

#25 Change userguide filename to full CAPS
  USERGUIDE.md
Labels: maintenance

#26 Move changelog.md to separate file
  CHANGELOG.md
  README.md
Labels: maintenance

#27 Add release script to generate zip file
  .github/workflows/release.yaml
Labels: bug

#29 Update pull request template
  .github/pull_request_template.md
Labels: maintenance

#30 Remove versioning from feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: maintenance

#19 1.4.0 release
  .docker/Dockerfile
  .docker/docker-compose.yml
  .docker/entrypoint.sh
  CHANGELOG.md
  USERGUIDE.md
  assets/RSS.png
  controllers/front/SmailyRssFeed.php
  modman
  smailyforprestashop.php
  translations/et.php
  views/js/smaily_module.js
  views/templates/admin/smaily_configure.tpl
Labels: release
